#ifndef _FWCONFIG_H_
#define _FWCONFIG_H_

#define FWCONFIG_HOLDPOWER_PIN 26
#define FWCONFIG_HOLDPOWER_DELAY_MS (30*1000)

#define FWCONFIG_SWITCH_PIN 21
#define FWCONFIG_SWITCH_HOLDDELAY_MS (1500)

// WS1228 as sanity led
#define FWCONFIG_WS1228B_PIN 18
#define HWCONFIG_WS1228B_LEDCOUNT (45)

#endif